### ISSUE TITLE
Merge demisjohn fork/transfer ownership

### ISSUE THREAD

**Issue by demisjohn** [kitchenknif/CAMFR#3]
Hello,

I was wondering if I could somehow take over ownership of this repo, and just add you as a maintainer.
Not sure of the exact logistics of that, but I assume it's possible somehow.  Happy to add anyone as collaborators, but I will actually take the time to look at pull requests etc.

GitHub looks like a perfect place to continue development and post upgrades to CAMFR, continuing it's excellent utility.  Although I'm not particularly great at coding up mathematical models, I will try to upgrade the package to keep it current (currently working on Python3 upgrade).  Maybe the community can help with actual modeling coding.

Let me know what you think.
-- Demis

**Comment by kitchenknif** [comment]
Hey, 
Don't see any problem with that, seems like the correct way forward, since I'm not currently working on the project.

**Comment by kitchenknif** [comment]
If I understand this correctly, https://help.github.com/articles/about-repository-transfers/ , 
For me to transfer ownership to you, you would first have to delete your fork.
So I guess you could do a pull request of all of your commits to this repository, then delete your fork and then I will transfer ownership.

**Comment by demisjohn** [comment]
Ok, I will mostly overwrite all your changes with mine.
Will submit the PR for brach `master` now.

Following these instructions to transfer the py35_compat branch:
https://stackoverflow.com/a/5884825/2453202
Also will find some way to transfer Issues, in which I've tried to document much of the work.

By the way, thanks for creating the GitHub repo from SourceForge in the first place, that was a great move.

--                             Demis                             --
°•Oo.oO•°*°•Oo. Sound  OK
<http://www.google.com/search?q=sound+ok+horn&tbm=isch>  Horn *°•Oo.oO•°*°•O
o.

**Comment by kitchenknif** [comment]
I'll transfer ownership once you move everything to this repo, cannot while your fork still exists.

**Comment by demisjohn** [comment]
I've transferred all issues, and **Deleted my repo!**
Go ahead and do the transfer.

Thanks!

**Comment by kitchenknif** [comment]
Done,
Thanks for stepping up to maintain this project!
